### ISSUE TITLE
update README.md with Kirby v2.0.6 and ffmpeg instructions

### ISSUE THREAD

**Issue by derhuerst** [fanningert/kirbycms-extension-video#1]
[Kirby 2.0.6 has been released](http://getkirby.com/blog/kirby-2-0-6) and the issue with file extensions containing numbers [seems to be gone](https://github.com/getkirby/kirby/commit/77c89b415b7e18fed41b5bcafbef21672ccf1546) . Please update the readme mentioning the new version.

The user still needs to provide the different video formats for the plugin, right? I wrote a [bash script](https://gist.github.com/derhuerst/0db51ba39231d6529644) that creates `.webm` and `.mp4` as well as low-quality versions using [ffmpeg](http://ffmpeg.org). I think it would be good to give user instructions on how to convert their videos.

**Comment by fanningert** [comment]
Thanks, I will integrate it in the next release. I am working currently on a new version with some new features. I think, a release next week is possible.
