### ISSUE TITLE
Not possible to disable controls: boolean-to-string comparison

### ISSUE THREAD

**Issue by rantonse** [fanningert/kirbycms-extension-video#7]
Hi, @fanningert,

https://github.com/fanningert/kirbycms-extension-video/blob/master/site/plugins/videoext/videoext.php#L141

`if ($this->getOption ( VideoExt::OPTION_CONTROLS ) == true)`

If `controls: false` is used in the tag, this condition is satisfied, and the controls fail to be disabled.

**Comment by fanningert** [comment]
Thanks, I corrected the bug.
